name: Code checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  code-checks:
    if: github.event.pull_request.draft == false
    timeout-minutes: 10
#    runs-on: [ self-hosted, linux ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10-dev'

      - name: Setup poetry
        run: |
          pip install --upgrade pip==23.3.2
          python -m pip install poetry==1.7.1
          poetry config virtualenvs.create false

      - name: Update apt cache
        run: sudo apt-get update

      - name: Install system packages
        run: sudo apt-get install -y build-essential libgmp-dev

      - name: Install deps
        run: poetry install --no-root

      - name: Lint
        run: make lint

      - name: Unit Test
        run: make test
